### ISSUE TITLE
Toolchain size is huge!

### ISSUE THREAD

**Issue by parheliamm** [UBERTC/uber-scripts#2]
After compiled by uber-scripts, all toolchain size is over 500MB. The arm-linux-androideabi-4.9 is over 1.9GB.
Would you please reduce the toolchain size?

**Comment by Cl3Kener** [comment]
The purpose behind UBERTC is to maximum compatibility and optimization for any cpu target.  UBERTC includes all needed toolchain components for them to work on almost any linux operating system and doesn't share any toolchain components with the host (which is what other custom toolchains do to reduce size).  I could drastically reduce the size of the toolchain but that would limit users to have to use my specific build environment in order for toolchains to work. 

I do see you point though, it would be nice to have small toolchains for those people that build for only one cpu target. I will keep this issue open and work on reducing the size of the cortex specific toolchains here in the future for those people that aren't building for several different devices.

**Comment by Cl3Kener** [comment]
@parheliamm  Linaro toolchain-eabi is 875 MB once you decompress it http://snapshots.linaro.org/android/~linaro-android/toolchain-5.1-2015.06/3/.  500MB isn't looking quite so bad after all.

**Comment by Cl3Kener** [comment]
Okay @parheliamm I've managed to shrink all of the toolchains to less than 1 GB.  arm-eabi should be about 400-450 MB (or less possibly) and arm-linux-androideabi should be 700-800 MB (or no more than 1 GB)  If you want to test these changes you'll have to use dev branches by running  repo init -u https://github.com/UBERTC/uber-manifest.git -b dev  Prebuilts will roll out after another week or two worth of testing.

**Comment by Cl3Kener** [comment]
Toolchains are much smaller now.  By comparison they are smaller than Linaro and SaberMod and I've removed everything I can that I don't consider essential.
