### ISSUE TITLE
Is there possibility to support aarch64-linux-android-5.x or 6.x?

### ISSUE THREAD

**Issue by parheliamm** [UBERTC/uber-scripts#5]
Currently, it seems like UBER only support aarch64-linux-android-4.9 for android source code build.
Do we have a plan to support aarch64-linux-android-5.3 or 6.0 for Android source code build?

**Comment by secuflag** [comment]
+1

would be nice to have also aarch64 versions.

**Comment by secuflag** [comment]
ping @Cl3Kener @emceethemouth @mdalexca

**Comment by DespairFactor** [comment]
@secuflag will look at it, just need to fix a couple things first

**Comment by DespairFactor** [comment]
This has been completed

**Comment by secuflag** [comment]
Thank you very much!
