### ISSUE TITLE
The toolchain size is huge.

### ISSUE THREAD

**Issue by parheliamm** [UBERTC/uber-scripts#7]
The toolchain size is huge.
aarch64-linux-android-6.x is over 800MB.
Is there possible to reduce the size?

**Comment by DespairFactor** [comment]
not sure why this matters

**Comment by kykdev** [comment]
Strip it

**Comment by secuflag** [comment]
@matthewdalex The size could be a problem for who want to upload builds on github:
- libexec/gcc/arm-eabi/6.4.1/cc1 (~126MB not stripped | ~19MB stripped)
- libexec/gcc/arm-eabi/6.4.1/cc1plus (~135MB not stripped | ~20MB stripped)
- libexec/gcc/arm-eabi/6.4.1/lto1 (~121MB not stripped | ~18MB stripped)

IMHO would be a really good idea strip all binary files once compiled.

**Comment by DespairFactor** [comment]
@secuflag what are you using to strip them?

**Comment by secuflag** [comment]
```
strip -s filename
```

**Comment by DespairFactor** [comment]
@secuflag will add stripping to the toolchain build scripts

**Comment by DespairFactor** [comment]
Done now in these commits:

https://github.com/UBERTC/uber-scripts/commit/71d102eb96369697cc3e7681de6a80632a9224fe
https://github.com/UBERTC/uber-scripts/commit/fd24715f5bceb9d7f3aaf911ff771a1b0ff8d66a

**Comment by secuflag** [comment]
Thanks!
